#This file illustrates some basic usage for the c2raytools package
#The script reads some data files and prints and plots some statistics

import numpy as np
import matplotlib as mpl
mpl.use('Agg')
import pylab as pl
import scipy.interpolate

mpl.rcParams['axes.linewidth'] = 1.5

#Some path names. Modify these as needed
one_filename = '../244Mpc_f2_0_250_pyt/results/dT_rsd_b5nu4_244Mpc_0_250.dat'
two_filename =	'../244Mpc_f2_8.2S_250_pyt/results/dT_rsd_b5nu4_244Mpc_8.2S_250.dat'
three_filename = '../244Mpc_f2_8.2pS_250_pyt/results/dT_rsd_b5nu4_244Mpc_8.2pS_250.dat'
four_filename = '../244Mpc_f2_gS_250_pyt/results/dT_rsd_b5nu4_244Mpc_gS_250.dat'
five_filename = '../244Mpc_f2_0_250_pyt/results/xfrac_244Mpc_f2_0_250.dat'
six_filename =	'../244Mpc_f2_8.2S_250_pyt/results/xfrac_244Mpc_f2_8.2S_250.dat'
seven_filename = '../244Mpc_f2_8.2pS_250_pyt/results/xfrac_244Mpc_f2_8.2pS_250.dat'
eight_filename = '../244Mpc_f2_gS_250_pyt/results/xfrac_244Mpc_f2_gS_250.dat'

#Read in dTx files files (z, nu, dT_mean, dTconv_mean, dTconv_rms, dTconv_skew)
f1 = np.loadtxt(one_filename)
f2 = np.loadtxt(two_filename)
f3 = np.loadtxt(three_filename)
f4 = np.loadtxt(four_filename)
f5 = np.loadtxt(five_filename)
f6 = np.loadtxt(six_filename)
f7 = np.loadtxt(seven_filename)
f8 = np.loadtxt(eight_filename)

pl.figure()
#pl.plot(f1[:,1],f1[:,3],'r-',label='L1',lw=1.5)
#pl.plot(f2[:,1],f2[:,3],'b:',label='L2',lw=2)
#pl.plot(f3[:,1],f3[:,3],'g--',label='L3',lw=2)
#pl.plot(f4[:,1],f4[:,3],'m-.',label='L4',lw=2)
pl.plot(f1[:,1],f1[:,3],'r',label='no LMACHs')
pl.plot(f2[:,1],f2[:,3],'b',label='supp LMACHs')
pl.plot(f3[:,1],f3[:,3],'g',label='psupp LMACHs')
pl.plot(f4[:,1],f4[:,3],'m',label='gsupp LMACHs')
pl.ylim([0,20])
pl.xlim([210,70])
#pl.title('rms source comparison')
pl.xlabel('$\textbf{\\nu \\rm{[MHz]}}$')
pl.ylabel('$<\delta T_{\\rm b}>^{1/2} \\rm{[mK]}$',fontsize=16)
pl.minorticks_on()
leg = pl.legend(loc='lower right',prop={'size':11})
leg.draw_frame(False)
#pl.savefig('./eps/dTrms_244_rsd_sources.eps')
pl.savefig('./pres/dTrms_244_rsd_sources.png', bbox_inches='tight')

pl.clf()
#pl.plot(f1[:,1],f1[:,6],'r-',lw=1.5,label='L1')
#pl.plot(f2[:,1],f2[:,6],'b:',lw=2,label='L2')
#pl.plot(f3[:,1],f3[:,6],'g--',lw=2,label='L3')
#pl.plot(f4[:,1],f4[:,6],'m-.',lw=2,label='L4')
pl.plot(f1[:,1],f1[:,7],'r',label='no LMACHs')
pl.plot(f2[:,1],f2[:,7],'b',label='supp LMACHs')
pl.plot(f3[:,1],f3[:,7],'g',label='psupp LMACHs')
pl.plot(f4[:,1],f4[:,7],'m',label='gsupp LMACHs')
pl.ylim([0,5])
pl.xlim([210,70])
#pl.title('rms Source comparison with 5" beam, 0.4 MHz')
pl.xlabel('$\\nu \\rm{[MHz]}$')
pl.ylabel('$<\delta T_{\\rm b}>^{1/2} \\rm{[mK]}$')
pl.minorticks_on()
leg = pl.legend(loc='lower right',prop={'size':11})
leg.draw_frame(False)
#pl.savefig('./eps/dTrms_244_rsd_b5nu4_sources.eps')
pl.savefig('./pres/dTrms_244_rsd_b5nu4_sources.png')

pl.clf()
#pl.plot(f1[:,1],f1[:,4],'r-',label='L1',lw=1.5)
#pl.plot(f2[:,1],f2[:,4],'b:',label='L2',lw=2)
#pl.plot(f3[:,1],f3[:,4],'g--',label='L3',lw=2)
#pl.plot(f4[:,1],f4[:,4],'m-.',label='L4',lw=2)
pl.plot(f1[:,1],f1[:,4],'r',label='no LMACHs')
pl.plot(f2[:,1],f2[:,4],'b',label='supp LMACHs')
pl.plot(f3[:,1],f3[:,4],'g',label='psupp LMACHs')
pl.plot(f4[:,1],f4[:,4],'m',label='gsupp LMACHs')
pl.ylim([0,15])
pl.xlim([210,70])
#pl.title('rms source comparison')
pl.xlabel('$\\nu \\rm{[MHz]}$')
pl.ylabel('$\\rm skewness$')
pl.minorticks_on()
leg = pl.legend(loc='upper right',prop={'size':11})
leg.draw_frame(False)
#pl.savefig('./eps/dTskew_244_rsd_sources.eps')
pl.savefig('./pres/dTskew_244_rsd_sources.png')

pl.clf()
#pl.plot(f1[:,1],f1[:,7],'r-',lw=1.5,label='L1')
#pl.plot(f2[:,1],f2[:,7],'b:',lw=2,label='L2')
#pl.plot(f3[:,1],f3[:,7],'g--',lw=2,label='L3')
#pl.plot(f4[:,1],f4[:,7],'m-.',lw=2,label='L4')
pl.plot(f1[:,1],f1[:,8],'r',label='no LMACHs')
pl.plot(f2[:,1],f2[:,8],'b',label='supp LMACHs')
pl.plot(f3[:,1],f3[:,8],'g',label='psupp LMACHs')
pl.plot(f4[:,1],f4[:,8],'m',label='gsupp LMACHs')
pl.ylim([-2,12])
pl.xlim([210,70])
#pl.title('rms Source comparison with 5" beam, 0.4 MHz')
pl.xlabel('$\\nu \\rm{[MHz]}$')
pl.ylabel('$\\rm skewness$')
pl.minorticks_on()
leg = pl.legend(loc='upper right',prop={'size':11})
leg.draw_frame(False)
#pl.savefig('./eps/dTskew_244_rsd_b5nu4_sources.eps')
pl.savefig('./pres/dTskew_244_rsd_b5nu4_sources.png')

pl.clf()
#pl.plot(f1[:,1],f1[:,2],'r-',lw=1.5,label='L1')
#pl.plot(f2[:,1],f2[:,2],'b:',lw=2,label='L2')
#pl.plot(f3[:,1],f3[:,2],'g--',lw=2,label='L3')
#pl.plot(f4[:,1],f4[:,2],'m-.',lw=2,label='L4')
pl.plot(f1[:,1],f1[:,2],'r',label='no LMACHs')
pl.plot(f2[:,1],f2[:,2],'b',label='supp LMACHs')
pl.plot(f3[:,1],f3[:,2],'g',label='psupp LMACHs')
pl.plot(f4[:,1],f4[:,2],'m',label='gsupp LMACHs')
pl.ylim([0,40])
pl.xlim([210,70])
#pl.title('mean dT source comparison')
pl.xlabel('$\\nu \\rm{[MHz]}$')
pl.ylabel('$\delta T_{\\rm b} \\rm{[mK]}$')
leg = pl.legend(loc='upper left',prop={'size':11})
leg.draw_frame(False)
#pl.savefig('./eps/dTmean_244_rsd_sources.eps')
pl.savefig('./pres/dTmean_244_rsd_sources.png')

pl.clf()
#pl.plot(f5[:,2],f1[:,3],'r-',lw=1.5,label='L1')
#pl.plot(f6[:,2],f2[:,3],'b:',lw=2,label='L2')
#pl.plot(f7[:,2],f3[:,3],'g--',lw=2,label='L3')
#pl.plot(f8[:,2],f4[:,3],'m-.',lw=2,label='L4')
pl.plot(f5[:,2],f1[:,3],'r',label='no LMACHs')
pl.plot(f6[:,2],f2[:,3],'b',label='supp LMACHs')
pl.plot(f7[:,2],f3[:,3],'g',label='psupp LMACHs')
pl.plot(f8[:,2],f4[:,3],'m',label='gsupp LMACHs')
pl.ylim([0,18])
pl.xlim([1.05,-0.05])
#pl.title('rms comparison vs. ionized fraction')
pl.xlabel('$x_{\\rm m}$')
pl.ylabel('$<\delta T_{\\rm b}>^{1/2} \\rm{[mK]}$')
pl.minorticks_on()
leg = pl.legend(loc='upper left',prop={'size':11})
leg.draw_frame(False)
#pl.savefig('./eps/dTrmsxi_244_rsd_sources.eps')
pl.savefig('./pres/dTrmsxi_244_rsd_sources.png')

pl.clf()
#pl.plot(f5[:,2],f1[:,6],'r-',lw=1.5,label='L1')
#pl.plot(f6[:,2],f2[:,6],'b:',lw=2,label='L2')
#pl.plot(f7[:,2],f3[:,6],'g--',lw=2,label='L3')
#pl.plot(f8[:,2],f4[:,6],'m-.',lw=2,label='L4')
pl.plot(f5[:,2],f1[:,7],'r',label='no LMACHs')
pl.plot(f6[:,2],f2[:,7],'b',label='supp LMACHs')
pl.plot(f7[:,2],f3[:,7],'g',label='psupp LMACHs')
pl.plot(f8[:,2],f4[:,7],'m',label='gsupp LMACHs')
pl.ylim([0,5])
pl.xlim([1.05,-0.05])
#pl.title('rms source comparison with 5" beam, 0.4 MHz')
pl.xlabel('$x_{\\rm m}$')
pl.ylabel('$<\delta T_{\\rm b}b>^{1/2} \\rm{[mK]}$')
pl.minorticks_on()
leg = pl.legend(loc='lower right',prop={'size':11})
leg.draw_frame(False)
#pl.savefig('./eps/dTrmsxi_244_rsd_b5nu4_sources.eps')
pl.savefig('./pres/dTrmsxi_244_rsd_b5nu4_sources.png')

